### ISSUE TITLE
cf deploy of mta file throwing panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by fahadibm** [cloudfoundry/multiapps-cli-plugin#220]
### Description
Describe your issue here. What is the expected behavior? What is the actual behavior?

### Your environment
*	MultiApps Controller version -  **multiapps 3.4.1**
*	MultiApps CF CLI Plugin version - **cf -v 8.8.2**
*	which CF vendor is used - **Downloaded from https://github.com/cloudfoundry/cli/wiki/V8-CLI-Installation-Guide**

### Steps to reproduce
build project using Cloud MTA Build Tool version 1.2.33. 
Command used mbt build

After build, deploy the mta file using:
cf deploy mta_archives/xxx.mta 
It is throwing the following error:

_panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0xa176ac]

goroutine 1 [running]:
github.com/cloudfoundry-incubator/multiapps-cli-plugin/commands.(*DeployCommand).getMtaArchive(0xb380d3?, {0xc0004126a0?, 0xc16818?, 0x1?}, {0x6?, 0x83?})
        /root/go/src/github.com/cloudfoundry-incubator/multiapps-cli-plugin/commands/deploy_command.go:543 +0x16c
github.com/cloudfoundry-incubator/multiapps-cli-plugin/commands.(*DeployCommand).executeInternal(0xc000342540, {0xc0004126a0, 0x1, 0x1}, {0xc00001ce40, 0x2c}, 0xc000400780, {{{{0xc0004389c0, 0x24}, {0xc00040e810, ...}, ...}}, ...})
        /root/go/src/github.com/cloudfoundry-incubator/multiapps-cli-plugin/commands/deploy_command.go:239 +0x205
github.com/cloudfoundry-incubator/multiapps-cli-plugin/commands.(*BaseCommand).Execute(0xc000191560, {0xc0000360b0, 0x1, 0x1})       
        /root/go/src/github.com/cloudfoundry-incubator/multiapps-cli-plugin/commands/base_command.go:122 +0x57a
main.(*MultiappsPlugin).Run(0xb39de3?, {0xc258f0, 0xc0002e7ba0}, {0xc0000360a0, 0x2, 0x2})
        /root/go/src/github.com/cloudfoundry-incubator/multiapps-cli-plugin/multiapps_plugin.go:45 +0x1e9
code.cloudfoundry.org/cli/plugin.Start({0xc1d658, 0x10b8180})
        /root/go/pkg/mod/code.cloudfoundry.org/cli@v7.1.0+incompatible/plugin/plugin_shim.go:34 +0x309
main.main()
        /root/go/src/github.com/cloudfoundry-incubator/multiapps-cli-plugin/multiapps_plugin.go:65 +0x27_

**Comment by Yavor16** [comment]
Hello, @fahadibm,
Do you regularly receive the exception that you got? Also when you got it, was the file valid, did it exist or did you pass any arguments that you haven't specified in the Issue?
Best regards,
Yavor
